In [51]:
from __future__ import print_function
import torch


In [52]:
x = torch.empty(5,3)
print(x)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [53]:
x = torch.rand(5,3)
print(x)

tensor([[0.2212, 0.7923, 0.7159],
        [0.1206, 0.3451, 0.6487],
        [0.6759, 0.9090, 0.9643],
        [0.6663, 0.6160, 0.2742],
        [0.5482, 0.5667, 0.2987]])


In [54]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [55]:
x = torch.tensor([5.5, 3])
print(x)
print(x.size())

tensor([5.5000, 3.0000])
torch.Size([2])


In [56]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4597,  0.0814, -2.3269],
        [-0.0835,  0.9280,  0.9468],
        [-0.2403, -1.1825,  0.9374],
        [ 1.0973, -1.3046,  1.4616],
        [ 0.2955,  0.4463, -0.2970]])


In [57]:
print(x.size())

torch.Size([5, 3])


In [58]:
y = torch.rand(5, 3)
print(x+y)

tensor([[ 2.2674,  0.3092, -1.4117],
        [ 0.5900,  1.0892,  1.8696],
        [ 0.5578, -1.1179,  1.9108],
        [ 1.9333, -0.5948,  1.9311],
        [ 1.0790,  1.4284, -0.2248]])


In [59]:
print(torch.add(x, y))

tensor([[ 2.2674,  0.3092, -1.4117],
        [ 0.5900,  1.0892,  1.8696],
        [ 0.5578, -1.1179,  1.9108],
        [ 1.9333, -0.5948,  1.9311],
        [ 1.0790,  1.4284, -0.2248]])


In [60]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.2674,  0.3092, -1.4117],
        [ 0.5900,  1.0892,  1.8696],
        [ 0.5578, -1.1179,  1.9108],
        [ 1.9333, -0.5948,  1.9311],
        [ 1.0790,  1.4284, -0.2248]])


In [61]:
y.add_(x)
print(y)

tensor([[ 2.2674,  0.3092, -1.4117],
        [ 0.5900,  1.0892,  1.8696],
        [ 0.5578, -1.1179,  1.9108],
        [ 1.9333, -0.5948,  1.9311],
        [ 1.0790,  1.4284, -0.2248]])


In [62]:
print(x[:, 1])

tensor([ 0.0814,  0.9280, -1.1825, -1.3046,  0.4463])


In [63]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 0.7053,  0.1070,  0.5111, -0.7097],
        [-0.8233,  1.3490,  1.0424, -0.2464],
        [-1.2136, -1.0479,  1.0968,  0.0431],
        [-0.6132,  0.4278, -0.5912, -0.3375]])
tensor([ 0.7053,  0.1070,  0.5111, -0.7097, -0.8233,  1.3490,  1.0424, -0.2464,
        -1.2136, -1.0479,  1.0968,  0.0431, -0.6132,  0.4278, -0.5912, -0.3375])
tensor([[ 0.7053,  0.1070,  0.5111, -0.7097, -0.8233,  1.3490,  1.0424, -0.2464],
        [-1.2136, -1.0479,  1.0968,  0.0431, -0.6132,  0.4278, -0.5912, -0.3375]])


In [64]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-2.4648])
-2.4648244380950928


In [65]:
# Numpy bridge
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [66]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [67]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [68]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [71]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

In [ ]:
import torch
print(torch.cuda.is_available())


False
